Addition of support for oneOf and anyOf along with its unit tests
apimatic/jsonmapper pull request #11
Opened 2021-12-02 06:11 UTC by asadali214

2022-01-12 08:36 UTC, sufyankhanrao reviewed
OneOf type deserialization of parent & child types with discriminators, is not working fine.

2022-01-12 08:38 UTC, sufyankhanrao reviewed
Follow code snippet can be simplified to minimal lines of code in _insertType utility.
![image](https://user-images.githubusercontent.com/18752818/149092432-a4772aa9-8fb1-4cac-b379-a409382c0be5.png)

2022-01-17 08:45 UTC, sufyankhanrao approved these changes
Approved.

2022-01-27 04:27 UTC, thehappybug requested changes
Your PR adds some IDE files and other temp files accidentally. Please update the gitignore file to ignore them. Here's a recommended set of rules: https://www.toptal.com/developers/gitignore/api/phpunit,composer,phpstorm

I am still going through the JsonMapper.php changes and have not fully understood them yet. But I'm submitting some of my comments so that you can fix the low-hanging fruits instead of waiting for me indefinitely.

Apart from the comments I made in the files, I have some questions:

1. Did you test whether your changes to the `@maps` annotation are catering to the case where a property might have a space in its serialized name? This was handled previously but in your tests, I didn't find a property with a space in the name being tested so I'm not sure if you are handling this case correctly.
2. Do your changes to the interfaces and the behavior of the library constitute a breaking change to the library?
3. What does the test coverage for the code look like right now and how has it changed since before the PR? Please attach the coverage report for before and after.

PS: @asadali214 When reading my comment on the code, note that the comments are on the last line of code. GitHub is showing 3 lines above that as well but my comment was actually placed on the last line of code. So in the first comment, my comment is about line 43 but GH is showing lines 40, 41, and 42 as well. Also note that sometimes, I comment about a general area of code rather than a specific line but my comment's text will make that clear to you.

2022-01-27 04:27 UTC, thehappybug commented on tests/multitypetest/MultiTypeTest.php
> +    public function testComplexCasesWithDescriminators()
```suggestion
    public function testComplexCasesWithDiscriminators()
```

2022-01-27 04:27 UTC, thehappybug commented on src/JsonMapper.php
> +    private function _callFactoryMethod($factoryMethod, $value, $className)
Using underscore to start a method name for a private method in not a convention in PHP. Please follow PHP's coding conventions.

2022-01-27 04:27 UTC, thehappybug commented on src/JsonMapper.php
> +use Exception;
You have put unrelated changes such as additional imports and refactoring of code due to the imports in the same PR as this feature implementation which makes it difficult for the reviewer to review your changes. Too much is changing at once. In the future, separate refactoring and other unrelated changes into their own separate PRs.

2022-01-27 04:27 UTC, thehappybug commented on src/TypeCombination.php
> + * @category Netresearch
There is not need to credit Netresearch. You do not work at Netresearch. You can remove this in the new files you create.

2022-01-31 08:31 UTC, asadali214 commented
> Did you test whether your changes to the @maps annotation are catering to the case where a property might have a space in its serialized name? This was handled previously but in your tests, I didn't find a property with a space in the name being tested so I'm not sure if you are handling this case correctly.

Yes I had missed this case during my implementation, so Now I have introduced another annotation `@mapsBy` to cater for oneOf/anyOf types

> Do your changes to the interfaces and the behavior of the library constitute a breaking change to the library?

No there is no breaking change to the library

> What does the test coverage for the code look like right now and how has it changed since before the PR? Please attach the coverage report for before and after.

Let me update this comment after getting the code coverage report

2022-01-31 08:57 UTC, thehappybug commented
> Yes I had missed this case during my implementation, so Now I have introduced another annotation `@mapsBy` to cater for oneOf/anyOf types

@asadali214 Is this change already pushed to this branch or are you still working on it?

2022-01-31 09:30 UTC, asadali214 commented
> @asadali214 Is this change already pushed to this branch or are you still working on it?

@thehappybug Yes I have already pushed this change to the branch

2022-01-31 10:07 UTC, thehappybug commented on src/JsonMapper.php
> +                        } catch (\Throwable $e){
I don't understand this part of the code; you are catching _all_ exceptions and then ignoring the exception to continue the loop. What is this for-loop doing and did you consider a better code than using exceptions in the main flow of your code (main flow meaning the normal running of the code)?

2022-01-31 10:08 UTC, thehappybug commented on src/JsonMapper.php
> +                        $this->_callFactoryMethod($method, $value, $className);
The code for when the php version is less than 7.0 and greater than 7.0 is basically the same with the exception of the additional exception handling you have done. I'm not sure why there's a difference. You should document this part of the code because it is not obvious to the reader what is happening and why.

2022-01-31 10:12 UTC, thehappybug commented on src/JsonMapper.php
> +    private function _isValueOfType(
This method seems to validate a value against some types. However, it attempts to reimplements the entire functionality of the JsonMapper library in this method including all the simple and complex types. Did you consider leaning on the existing implementation to help you validate the data against various cases of the any-of/one-of combinators? What did the existing methods lack that you had to reimplement the whole validation in this method?

2022-02-01 11:53 UTC, asadali214 commented
> What does the test coverage for the code look like right now and how has it changed since before the PR? Please attach the coverage report for before and after.

@thehappybug I have zipped html form of code coverage on master and this branch
This Branch: [NewCodeCoverageJsonMapper.zip](https://github.com/apimatic/jsonmapper/files/7978157/NewCodeCoverageJsonMapper.zip)
Master: [OldCodeCoverageJsonMapper.zip](https://github.com/apimatic/jsonmapper/files/7978158/OldCodeCoverageJsonMapper.zip)

2022-02-03 05:31 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +    public function testSimpleCaseAFail()
I have applied this to the full test file, and now all the unit tests are as small as possible

2022-02-03 05:34 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +        $this->assertTrue(strpos($res, 'Could not find required constructor arguments for') === 0);
Now I am testing the full exception message instead of just a part of it, Instead of this I am also testing out the type of exception thrown in each case

2022-02-03 05:34 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +        $this->assertTrue(strpos($res, 'Unable to map AnyOf') === 0);
A full error message is added now

2022-02-03 05:36 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +        $res = $mapper->mapFor(json_decode($json), 'oneOf(null,array,bool)');
Yes this is how we are dealing associative arrays with "array" in rest of the jsonMapper

2022-02-03 05:37 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +            $mapper->mapFor(json_decode($json), 'oneOf(array,bool)');
json_decode(null) returns null, but yes this is an extra step, and now I am avoiding it by just replacing it with null

2022-02-03 05:38 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +        $json = '"{\"value\":[1.2]}"';
Sorry, I have now fixed this

2022-02-03 05:39 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +        $this->assertTrue(strpos($res, 'Cannot map more then OneOf') === 0);
Fixed!

2022-02-03 05:41 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +    public function testComplexCasesWithDescriminators()
Fixed!

2022-02-03 06:10 UTC, asadali214 commented on src/JsonMapper.php
> +     */
Thanks for pointing out, I have now improved the doc block for "mapFor"

2022-02-03 06:10 UTC, asadali214 commented on src/JsonMapper.php
> +    private function _callFactoryMethod($factoryMethod, $value, $className)
Fixed!

2022-02-03 06:12 UTC, asadali214 commented on src/JsonMapper.php
> +use Exception;
Thank you for pointing out, I will keep this in mind!

2022-02-03 06:12 UTC, asadali214 commented on src/TypeCombination.php
> + * @category Netresearch
Fixed!

2022-02-07 10:29 UTC, asadali214 commented on src/JsonMapper.php
> +    private function _isValueOfType(
Fixed

2022-02-08 10:53 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +            // oneof Orbit (did not have # of protons) & Atom (have # of protons optional)
No, its the behavior of jsonMapper that it only look at the required fields, if all required fields of a type are present in a json then it maps the type onto that json. So in this case Atom & Orbit both have numberOfElectrons as required field, hence json will be mapped by both of the types, and additional fields are added as optional properties or additional properties (if enabled)

2022-02-08 10:57 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +            $res = $e->getMessage();
Fixed

2022-02-08 10:57 UTC, asadali214 commented on tests/multitypetest/MultiTypeTest.php
> +            $res = $e->getMessage();
Fixed

2022-02-09 08:33 UTC, asadali214 commented on src/JsonMapper.php
> +                        } catch (\Throwable $e){
This loop is checking for each deserializer function seprately if any one can be used to deserailze the given value, and yes there is no other way to check if a deserializer function is throwing an exception or running as expected, since it will be user defined

2022-02-09 08:34 UTC, asadali214 commented on src/JsonMapper.php
> +                        $this->_callFactoryMethod($method, $value, $className);
I have added more docs to explain what is going on here

2022-02-14 14:59 UTC, thehappybug approved these changes
The new changes look good to me. 

I leave it to @asadali214 to figure out whether we want a second review or not. From my side, the PR is approved.

2022-02-15 04:54 UTC, asadali214 commented
> please turn this into an issue.

Issue Created: https://github.com/apimatic/jsonmapper/issues/12

2022-02-16 07:15 UTC, sufyankhanrao approved these changes
Approved.

2022-02-16 07:35 UTC, merged