Throw a JsonMapperException if php configuration discards comments.
apimatic/jsonmapper pull request #14
Opened 2022-05-18 07:04 UTC by Mohammad-Haris

2022-05-19 05:11 UTC, asadali214 commented on src/JsonMapperException.php
> +    static function commentsDisabledInConfigurationException($concernedKeys)
Very good approach to define exception messages in JsonMapperException class

2022-05-19 05:21 UTC, asadali214 commented
This change looks good but we need to add its unit test that test this Exception being thrown and compare the exception message

checkout unitTest: JsonMapperTest::testMapClassWithNonObject() to see how to expect an exception and its message

2022-05-19 05:22 UTC, asadali214 requested changes
Kindly add the unit test to test this change

2022-05-19 06:45 UTC, Mohammad-Haris commented on src/JsonMapperException.php
> +    static function commentsDisabledInConfigurationException($concernedKeys)
Not an original idea, saw this approach being used in the annotations repo you linked in the bug.
I probably would have gone with a function, but not exactly. The static function creating the object internally is good.

2022-05-19 07:02 UTC, asadali214 commented on src/JsonMapper.php
> +    function __construct()
This constructor is throwing an Exception, please add the throws tag for it

2022-05-23 07:38 UTC, asadali214 approved these changes
These changes looks good to me
Good work done @Mohammad-Haris

2022-05-23 07:49 UTC, merged