Added functions for validation of oneof/anyof params by type
apimatic/jsonmapper pull request #27
Opened 2022-06-08 11:38 UTC by asadali214

Closes #25

2022-06-09 20:14 UTC, sufyankhanrao commented on src/TypeCombination.php
> +    public function extractOneOfAnyOfGroup()
Is there a way that we can provide test coverage for this method?

2022-06-09 20:50 UTC, sufyankhanrao requested changes
1st review done.

2022-06-10 07:53 UTC, asadali214 commented on src/TypeCombination.php
> +    public function extractOneOfAnyOfGroup()
You can run the following command to generate test coverage report for the library
`vendor/bin/phpunit --coverage-html CodeCoverage .\tests\`
This will generate a file under root folder of library `CodeCoverage\index.html` you can view that report to find that all the methods in TypeCombination class are already covered in existing tests i.e:
![image](https://user-images.githubusercontent.com/26116671/173018151-68bbda74-5bed-4b32-9881-29181279e5d0.png)

2022-06-10 07:55 UTC, asadali214 commented on src/TypeCombination.php
> +    public function extractSimilar($group)
This method is also fully covered via existing tests

2022-06-10 07:59 UTC, asadali214 commented on src/JsonMapper.php
> +                if (is_string($t)) {
I am now triming the white spaces at line 277 in TypeCombination.php

2022-06-10 09:16 UTC, asadali214 commented on src/JsonMapper.php
> +        switch ($type) {
Done

2022-06-10 10:20 UTC, sufyankhanrao approved these changes
Change looks good to me.

2022-06-13 08:23 UTC, sufyankhanrao approved these changes
Approved

2022-06-13 08:54 UTC, merged